### ISSUE TITLE
game crashed while starting up

### ISSUE THREAD

**Issue by Hellscaped** [homchom/recode#12] opened 2022-09-11 20:14 UTC
The game crashed whilst initializing game
Error: java.lang.UnsatisfiedLinkError: 'void io.github.homchom.recode.shaded.org.newsclub.net.unix.NativeUnixSocket.connect(java.lang.String, java.io.FileDescriptor)'

**Comment by homchom** [comment] 2022-09-11 20:16
duplicate of #9, but not your fault because the original reporter closed the issue

**Closed as completed by homchom** 2022-09-11 20:16 UTC
